# Generated by Django 3.1.5 on 2021-06-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_table',
            name='blog_html',
        ),
        migrations.RemoveField(
            model_name='blog_table',
            name='media_id',
        ),
    ]
